[package]
name = "greed_console"
version = "0.11.0-devel"
edition = "2021"
authors = ["Claire Moore <kurennon@gmail.com>"]
rust-version = "1.71"
description = "A small GUI App to help with playing Greed"
license = "GPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
eframe = { version = "0.22.0", features = ["persistence"] }
egui = "0.22.0"
egui_dock = "0.6.3"
egui-notify = "0.8.0"
env_logger = "0.10"
google-docs1 = "5.0.3"
indexmap = { version = "2.0.0", features = ["serde"] }
log = "0.4.20"
rfd = "0.12.0"
ron = "0.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0.47"

[build-dependencies]
nsvg = "0.5.1"
