[package]
name = "greed_console"
version = "0.8.0-devel"
edition = "2021"
authors = ["Claire Moore <kurennon@gmail.com>"]
rust-version = "1.65"
description = "A small GUI App to help with playing Greed"
license = "GPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
eframe = { version = "0.22.0", features = ["persistence"] }
log = "0.4.19"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
tokio = { version = "1", features = ["full"] }
google-docs1 = "5.0.2"
thiserror = "1.0.40"
egui_file = "0.9.0"
indexmap = { version = "2.0.0", features = ["serde"] }
egui-notify = "0.7.0"

[build-dependencies]
nsvg = "0.5.1"
