name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
env:
  preview: ${{ !startsWith(github.ref, 'refs/tags/') }}
jobs:
  release:
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        build: [x86_64-linux, x86_64-macos, aarch64-macos, x86_64-windows]
        include:
        - asset_suffix: ""
        - build: x86_64-linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - build: x86_64-macos
          os: macos-latest
          target: x86_64-apple-darwin
        - build: aarch64-macos
          os: macos-latest
          target: aarch64-apple-darwin
        - build: x86_64-windows
          os: windows-latest
          target: x86_64-pc-windows-gnu
        - os: windows-latest
          asset_suffix: .exe
    name: release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: projects/${{ secrets.GOOGLE_PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.GOOGLE_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      - run: gcloud services api-keys create --display-name="Greed Console API Key, ${{ github.ref_name }}:${{ matrix.build }}" --key-id "${{ github.ref_name}}-${{ matrix.build }}"--api-target=service=drive.googleapis.com
      - run: |
          echo "APP_KEY=$(gcloud services api-keys get-key-string projects/${{ secrets.GOOGLE_PROJECT_NUM }}/locations/global/keys/${{ github.ref_name }}-${{ matrix.build }} | sed -e 's/keyString: //g')" >> $GITHUB_ENV
      - if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev
          version: 1.0
          execute_install_scripts: true
      - run: cargo build --all-features --release --target ${{ matrix.target }}
      - if: env.preview == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/${{ matrix.target }}/release/*
          asset_name: greed_console_$tag_${{ matrix.target }}${{ matrix.asset_suffix }}
