name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
env:
  preview: ${{ !startsWith(github.ref, 'refs/tags/') }}
jobs:
  release:
    env:
      API_KEY:
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        build: [x86_64-linux, x86_64-macos, aarch64-macos, x86_64-windows]
        include:
        - build: x86_64-linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          asset_suffix: ""
          key_prefix: linux-amd64
        - build: x86_64-macos
          os: macos-latest
          target: x86_64-apple-darwin
          asset_suffix: ""
          key_prefix: macos-amd64
        - build: aarch64-macos
          os: macos-latest
          target: aarch64-apple-darwin
          asset_suffix: ""
          key_prefix: macos-arm64
        - build: x86_64-windows
          os: windows-latest
          target: x86_64-pc-windows-gnu
          asset_suffix: .exe
          key_prefix: windows-gnu-amd64
    name: release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Authenticate to Google
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: projects/${{ secrets.GOOGLE_PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.GOOGLE_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 456.0.0'
      - name: Get or Create API Key
        shell: bash
        run: |
          export API_KEY_NAME=$(echo "${{ matrix.key_prefix }}-${{ github.ref_name }}" | sed -e 's|\.|_|g')
          if gcloud services api-keys describe $API_KEY_NAME >/dev/null 2>&1; then
            echo "Key Already Created"
          else
            gcloud services api-keys create --display-name="Greed Console API Key, ${{ github.ref_name }}:${{ matrix.build }}" --key-id $API_KEY_NAME --api-target=service=drive.googleapis.com >/dev/null 2>&1
          fi
          echo "API_KEY=$(gcloud services api-keys get-key-string projects/${{ secrets.GOOGLE_PROJECT_NUM }}/locations/global/keys/$API_KEY_NAME | sed -e 's/keyString: //g')" >> $GITHUB_ENV
      - name: Get Linux Libraries
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev
          version: 1.0
          execute_install_scripts: true
      - name: Install cargo for ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Set up Cargo Cache
        uses: Swatinem/rust-cache@v2
      - name: Build Binary
        run: cargo build --all-features --release --target ${{ matrix.target }}
      - name: Upload release
        if: env.preview == 'false'
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/${{ matrix.target }}/release/greed_console${{ matrix.asset_suffix }}
          asset_name: greed_console_$tag_${{ matrix.target }}${{ matrix.asset_suffix }}
